# Generated by Django 4.1.6 on 2023-02-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction",
                    models.IntegerField(
                        choices=[
                            (1, "Terrible"),
                            (2, "Bad"),
                            (3, "Okay"),
                            (4, "Good"),
                            (5, "Great"),
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("email", models.CharField(max_length=122)),
                ("password", models.CharField(max_length=122)),
                ("date", models.DateField()),
            ],
        ),
    ]
